### PR TITLE
Drop support for Python 2.7 up to 3.6

### PR DESCRIPTION
**Pull request by icemac**
Build using https://github.com/zopefoundation/meta/pull/178

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Comment by jamadden** [comment]
Can this please wait? I don't see the urgency in dropping in here. The comments I made earlier about keeping Python 2 support in the low-level libraries used outside of Zope are still relevant, I believe.

**Comment by dataflake** [comment]
Can those low-level libraries outside of Zope not pin to a specific version?

**Comment by jamadden** [comment]
They could, until such time as there is a bugfix or improvement. Then they're out in the cold. Or there's some complex back-porting process that results in dual releases and strange version numbers in order to keep pins working as desired.

**Comment by dataflake** [comment]
I see two ways forward:

- don't drop Python 2, but that also requires reverting the earlier dropping of Python 3.5 as that creates a package that's no longer compatible with Zope 4
- go forward with this PR because there's hardly any activity (bugfixes, features, etc) if I look at the open and closed issues. There is not any danger of too much extra work due to separate branches and releases.

I'm neutral on both.

**Comment by jamadden** [comment]
I'd strongly prefer to keep Python 2 support.  As the saying goes, "If it ain't broke, don't fix it."

I don't fully understand "but that also requires reverting the earlier dropping of Python 3.5 as that creates a package that's no longer compatible with Zope 4."

**Comment by dataflake** [comment]
> I don't fully understand "but that also requires reverting the earlier dropping of Python 3.5 as that creates a package that's no longer compatible with Zope 4."

Because Zope 4 officially supports Python 3.5. It follows that you cannot just remove that support from packages that claim full compatibility with Zope 4.

**Comment by icemac** [comment]
Okay, let's set this PR on hold until we reach consensus that the time has come for the low level libraries to finally drop Python 2 support.

**Comment by jamadden** [comment]
I appreciate the stay of execution. I know of organizations still working hard on a final Py2-Py3 transition. (In our case, we have on the order of a terabyte of ZODB data and a million lines of Python code we're transitioning.)

**Pull request merged**
