### PR TITLE
Preliminary support for Python 3.13a3

### LINKED ISSUE #55: Uses deprecated API PyEval_CallObjectWithKeywords, raises warnings under 3.10
### What I did:

I was running the tests of Zope with tox in a fresh environment with no pre-compiled eggs.

### What I expect to happen:

Installation without any warnings.

### What actually happened:

```
Getting distribution for 'Acquisition==4.8'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
src/Acquisition/_Acquisition.c: In function ‘CallMethod’:
src/Acquisition/_Acquisition.c:133:5: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
  133 |     result = PyEval_CallObjectWithKeywords(callable, args, kwargs);
      |     ^~~~~~
In file included from /usr/include/python3.10/Python.h:144,
                 from include/ExtensionClass/ExtensionClass.h:83,
                 from src/Acquisition/_Acquisition.c:15:
/usr/include/python3.10/ceval.h:17:43: note: declared here
   17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Got Acquisition 4.8.

```
### What version of Python and Zope/Addons I am using:
Linux
Python 3.10 via tox
Zope on this commit https://github.com/zopefoundation/Zope/tree/314683f66cc705d162a35436b1c7178ddb5f409d

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [X] Fixes #55 – replace deprecated C function
- [x] Error in test test_cant_persist_acquisition_wrappers_classic (Acquisition.tests.TestPickle.test_cant_persist_acquisition_wrappers_classic)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 636, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/Users/runner/work/Acquisition/Acquisition/src/Acquisition/tests.py", line 1520, in test_cant_persist_acquisition_wrappers_classic
    pickler.persistent_id = persistent_id
AttributeError: '_pickle.Pickler' object attribute 'persistent_id' is read-only
- [x] Error in test test_cant_persist_acquisition_wrappers_newstyle (Acquisition.tests.TestPickle.test_cant_persist_acquisition_wrappers_newstyle)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 6[36](https://github.com/zopefoundation/Acquisition/actions/runs/7760931015/job/21168908781?pr=68#step:9:37), in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/Users/runner/work/Acquisition/Acquisition/src/Acquisition/tests.py", line 1579, in test_cant_persist_acquisition_wrappers_newstyle
    pickler.persistent_id = persistent_id
AttributeError: '_pickle.Pickler' object attribute 'persistent_id' is read-only

### CODE REVIEW

**Comment by icemac** [comment]
Note: I personally do not plan to work on fixing these tests.

**Comment by davisagli** [comment]
@icemac I added a proposed fix for the failing tests on Python 3.13.0a3

**Comment by icemac** [comment]
@davisagli Thank you for fixing the tests.

**Review by d-maurer — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for working on resp. reviewing this PR. 😃

**Comment by icemac** [comment]
Hm, https://github.com/zopefoundation/zope.copy/issues/15 shows a similar traceback but there it seems to be in the actual code instead of beeing just in the tests.

**Pull request merged**
