### PR TITLE
try to get CI working again (Travis -> GHA)

### PR DESCRIPTION
**Pull request by d-maurer**

### CODE REVIEW

**Comment by d-maurer** [comment]
@icemac I fear I cannot switch from Travis -> GHA -- for lack of permissions (to get rid of Travis) and experience (with GHA).
My first trial run the GHAs but many failed because `zope.testrunner` was not installed and many have been canceled. In addition, the Travis and Appveyor tests were started -- likely due to push rules.
When I tried to add an installation request for `zope.testrunner` (in `.github/workflows/tests.yml`), the GHAs were no longer run. I do not know why.

Note: `zope.testrunner` installation should likely be ensured by `meta/config/c-code/tests.yml.j2`.

**Comment by d-maurer** [comment]
The change in `.manylinux-install.sh` is likely not necessary: almost surely, the `zope-testrunner` related problems have been caused by the missing `zope.testrunner` dependency in `tox.ini` (which should get fixed in `meta`).

**Comment by dataflake** [comment]
> The change in `.manylinux-install.sh` is likely not necessary: almost surely, the `zope-testrunner` related problems have been caused by the missing `zope.testrunner` dependency in `tox.ini` (which should get fixed in `meta`).

Other packages satisfy that dependency with an extra defined in `setup.py`, which is already picked up in `tox.ini`. See here for an example:

https://github.com/zopefoundation/ExtensionClass/blob/f6678f5ea62cf04ed0a998b2a6b08c81d4559864/setup.py#L82-L85

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2021-6-24 03:01 -0700:
>> The change in `.manylinux-install.sh` is likely not necessary: almost surely, the `zope-testrunner` related problems have been caused by the missing `zope.testrunner` dependency in `tox.ini` (which should get fixed in `meta`).
>
>Other packages satisfy that dependency with an extra defined in `setup.py`, which is already picked up in `tox.ini`. See here for an example:
>
>https://github.com/zopefoundation/ExtensionClass/blob/f6678f5ea62cf04ed0a998b2a6b08c81d4559864/setup.py#L82-L85

The `zope-testrunner` invocation comes from
`meta/config/default/tox-testenv.j2`. Consequently, it would
be natural to define also the dependency there.

**Comment by icemac** [comment]
> The `zope-testrunner` invocation comes from `meta/config/default/tox-testenv.j2`. Consequently, it would be natural to define also the dependency there.

It has been there but there is at least `zope.interface` which wants to run its tests without `zope.testrunner` and `RestrictedPython` which uses `pytest`, so we no longer automatically add `zope.testrunner` via `tox.ini` but expect that it is either installed via the `test` extra or configured via `.meta.toml` – this might be not ideal but it is the current status quo.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2021-7-12 23:24 -0700:
>> The `zope-testrunner` invocation comes from `meta/config/default/tox-testenv.j2`. Consequently, it would be natural to define also the dependency there.
>
>It has been there but there is at least `zope.interface` which wants to run its tests without `zope.testrunner` and `RestrictedPython` which uses `pytest`, so we no longer automatically add `zope.testrunner` via `tox.ini` but expect that it is either installed via the `test` extra or configured via `.meta.toml` – this might be not ideal but it is the current status quo.

The invocation of `zope-testrunner` is added automatically if
there are no other test commands. If `zope-testrunnner` is
added automatically as test command, it should (and can) be added automatically
as dependency.

**Review by icemac — APPROVED** [review]
LGTM.

**Pull request merged**
