### PR TITLE
When temporarily decoding an incoming attribute name from a unicode string, be careful not to destroy the temoporary PyObject until we're done using its char* buffer

### PR DESCRIPTION
**Pull request by jamadden**
Fixes zopefoundation/Acquisition#5, with luck.

### CODE REVIEW

**Comment by tseaver** [comment]
I'm sorry to ask, but can you find a way to split out the whitespace cleanups from the substantive change?  Changes to C extensions are tricky enough to review without the extra noise.  Even dividing them into two commits would be fine.

**Comment by jamadden** [comment]
Sorry about that. I often forget to turn that off in emacs. Too bad github doesn't have the equivalent of the '-w' option. Should be better now.

**Comment by tseaver** [comment]
Thank you!

**Comment by davisagli** [comment]
> Too bad github doesn't have the equivalent of the '-w' option. Should be better now.

It does! Add ?w=1 to the URL to see the diff with whitespace changes ignored.

**Comment by jamadden** [comment]
@davisagli Thank you!

**Pull request merged**
